#از عمد میتوانیم خودمون ارور درست کنیم
raise ValueError("نام معتبر نیست")